[package]
name = "rgasolineira"
version = "0.1.0"
edition = "2024"

[dependencies]
rustautogui = "2.5.0"
rand = "0.9.1"
clap = {version = "4.5.40", features = ["cargo"]}
chrono = "0.4.41"
image = "0.25"
reqwest = {version = "0.12.22", features = ["blocking"]}